version: "3.4"

services:
  database:
    image: postgres:12.1
    ports: 
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app: 
    build                                                                                                                                                                 :
      context: .
    command: rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - database
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/usr/app/node_modules
    environment:
      RAILS_ENV: development
      RUBYOPT: --enable-frozen-string-literal
    env_file: .env

volumes:
  gem_cache:
  db_data:
  node_modules: 